on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install gox
        run: go get github.com/mitchellh/gox
      - name: Build
        run: gox
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: supervisord_*
        env:
          GOFLAGS: "-trimpath"
