on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          go get github.com/mitchellh/gox
          export PATH="$(go env GOPATH)/bin:$PATH"
          gox -os="windows linux darwin" -osarch="!darwin/arm !darwin/arm64"
          mkdir dist
          mv supervisord_* dist/
        env:
          GOFLAGS: "-trimpath"
      - uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: dist/
